source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
xcodeproj 'ThemisUXTestExample/ThemisUXTestExample.xcodeproj'
inhibit_all_warnings!

target :"ThemisUXTestExample" do

  pod 'themis', '0.9'

  # stanfy
  pod 'SFCoreUtils', :git => 'https://github.com/stanfy/SFCoreUtils.git', :tag => '0.1.10'

  # RAC
  pod 'ReactiveCocoa', '~> 2.5'

  # nimbus
  pod 'AFNetworking', '~> 2.5.4'

end